version: '3.8'
services:
  database:
    image: postgres:16.2-bullseye
    restart: unless-stopped
    env_file:
      - ../../.env
    volumes:
      - journal_dev_data:/var/lib/postgresql/data
    networks:
      - journal-dev-network
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  server:
    build:
      context: ../../.
      dockerfile: ./_docker/dev/server/Dockerfile
    restart: unless-stopped
    volumes:
      - ../../server:/app
      - /app/node_modules
    env_file:
      - ../../.env
    networks:
      - journal-dev-network
    expose:
      - "4200"
    ports:
      - "4200:4200"
    depends_on:
      - database

  client:
    restart: unless-stopped
    build:
      context: ../../.
      dockerfile: _docker/dev/client/Dockerfile
    volumes:
      - ../../client/:/app/
      - /app/node_modules
      - /app/.next
    env_file:
      - ../../.env
    networks:
      - journal-dev-network
    environment:
      PORT: "3000"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - server
  proxy:
    build:
      context: ../../.
      dockerfile: _docker/dev/proxy/Dockerfile
    volumes:
      - ../../dev-proxy:/app
      - /app/node_modules
    networks:
      - journal-dev-network
    ports:
      - "4201:4201"

networks:
  journal-dev-network:
    driver: bridge
volumes:
  journal_dev_data:
    driver: local