import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { Providers } from './providers'

const zen = Noto_Sans({ 
  subsets: ["cyrillic",'latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-zen',
  style: ['normal']
})

export const metadata: Metadata = {
  title: {
    default: 'planner',
    template: `%s | planner`
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={zen.className}>
        <Providers>
         {children}
         <Toaster 
          theme='dark'
          position='bottom-right'
          duration={1500}
         />
        </Providers>
      </body>
    </html>
  )
}
